## Data Exploration and Cleaning

In [2]:
# importing the required libraries
import pandas as pd

In [3]:
# loading the dataset into a pandas data frame
df = pd.read_csv('../dataset/raw/customer_shopping_analysis.csv')

In [4]:
# viewing the first 5 rows of the dataset
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
# checking the count of rows and columns in the dataset
df.shape

(3900, 18)

In [6]:
# checking the summary statistics of numeric columns
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
# checking the summary statistics of all columns
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
# chekcing the count of null values
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
# filling missing 'Review Rating' values using the median rating of each 'Category'
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
# verifying that missing values were filled
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
# convert column names to lowercase snake_case
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

## Feature Engineering

In [14]:
# creating a column age group
bins = [0, 25, 35, 50, 120]
labels = [
    "0-25 Young Adult",
    "26-35 Adult",
    "36-50 Middle-aged",
    "50+ Senior"
]

df["age_group"] = pd.cut(
    df["age"],
    bins=bins,
    labels=labels,
    right=True
)

In [15]:
df[['age', 'age_group']]

      age          age_group
0      55         50+ Senior
1      19   0-25 Young Adult
2      50  36-50 Middle-aged
3      21   0-25 Young Adult
4      45  36-50 Middle-aged
...   ...                ...
3895   40  36-50 Middle-aged
3896   52         50+ Senior
3897   46  36-50 Middle-aged
3898   44  36-50 Middle-aged
3899   52         50+ Senior

[3900 rows x 2 columns]

In [16]:
# counting how many records fall into each frequency_of_purchases group
df.groupby('frequency_of_purchases')['frequency_of_purchases'].count()

frequency_of_purchases
Annually          572
Bi-Weekly         547
Every 3 Months    584
Fortnightly       542
Monthly           553
Quarterly         563
Weekly            539
Name: frequency_of_purchases, dtype: int64

In [17]:
# mapping purchase frequency labels to approximate number of days
frequency_mapping = {
    'Annually' : 365,
    'Bi-Weekly' : 14,
    'Every 3 Months' : 90,
    'Fortnightly' : 15,
    'Monthly' : 30,
    'Quarterly' : 90, 
    'Weekly' : 7   
}

# creating column purchase_frequency_in_days
df['purchase_frequency_in_days']  = df['frequency_of_purchases'].map(frequency_mapping)

In [18]:
df[['frequency_of_purchases','purchase_frequency_in_days']].head(10)

  frequency_of_purchases  purchase_frequency_in_days
0            Fortnightly                          15
1            Fortnightly                          15
2                 Weekly                           7
3                 Weekly                           7
4               Annually                         365
5                 Weekly                           7
6              Quarterly                          90
7                 Weekly                           7
8               Annually                         365
9              Quarterly                          90

In [19]:
# checking for redundancy
(df['discount_applied'] == df['promo_code_used']).all()

True

In [20]:
# removing the promo_code_used column from the data
df = df.drop('promo_code_used', axis = 1)

## Saving the cleaned data as a CSV file

In [22]:
df.to_csv("../dataset/processed/customer_shopping_cleaned.csv", index = False)

# Connecting Python script to PostgreSQL

In [24]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.12/site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.12/site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from sqlalchemy) (4.11.0)

In [25]:
from sqlalchemy import create_engine

# Step 1: Connecting to PostgreSQL
username = "sturdyskull"     
password = "1234" 
host = "localhost"        
port = "5432"
database = "customer_shopping_activity_db"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Loading DataFrame into PostgreSQL
table_name = "customer"   
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_shopping_activity_db'.